apiVersion: v2
name: honeybeepf-otel-collector
description: A Helm chart for otel collector
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: opentelemetry-collector
    version: "0.143.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"